export const portfolioTypes = {
  BackEnd: "Back-End",
  Blockchain: "Blockchain",
  FullStack: "Full-Stack",
};
export const portfolioData = [
  {
    type: portfolioTypes.Blockchain,
    name: "Plethori project",
    client: "Plethori",
    languages: "GatsBy, Web3 integration",
    preview: "https://plethori.com/",
    image: "img/projects/plethori.png",
  },
  {
    type: portfolioTypes.BackEnd,
    name: "VAPORBLITZ project",
    client: "VAPORBLITZ",
    languages: "React, Tailwindcss, Web3 integration",
    preview: "https://vaporblitz.io/",
    image: "img/projects/vaporblitz.png",
  },
  {
    type: portfolioTypes.BackEnd,
    name: "Fuzzy.one project",
    client: "Fuzzy.one",
    languages: "React",
    preview: "https://fuzzy.one/",
    image: "img/projects/fuzzy.png",
  },
  {
    type: portfolioTypes.BackEnd,
    name: "GOSA project",
    client: "GOSA",
    languages: "React",
    preview: "https://gosaverse.io/",
    image: "img/projects/gosa.png",
  },
  {
    type: portfolioTypes.BackEnd,
    name: "Devious Marketplace",
    client: "Fitz",
    languages: "React, Ant Design",
    preview: "https://devious.on.fleek.co/",
    image: "img/projects/devious.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Plethroi Bridge project",
    client: "Plethori",
    languages: "React, Solidity",
    preview: "https://plebridge.web.app/",
    image: "img/projects/plethori-bridge.png",
  },
  {
    type: portfolioTypes.Blockchain,
    name: "Devious Licks DGOLD",
    client: "Fitz",
    languages: "Solidity",
    preview:
      "https://bscscan.com/address/0x9e545b66afad4836656601b0a6c6c4508b33e2c4",
    image: "img/projects/devious-licks-token.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Moon Roll",
    client: "Moon",
    languages: " React, Tailwindcss, Express, Web3 integration",
    preview: "https://moonroll.io/",
    image: "img/projects/moon-roll.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "IMBUE",
    client: "Carrabre",
    languages: " React, Tailwindcss, Solidity, Livepeer",
    preview: "https://imbue.on.fleek.co/",
    image: "img/projects/imbue.png",
  },
  {
    type: portfolioTypes.FullStack,
    name: "Swappery",
    client: "Casper",
    languages:
      " React, Tailwindcss,Styled Component, Web3 integration, Solidity",
    preview: "https://www.the-swappery.com/",
    image: "img/projects/swappery.png",
  },
];
